baseURL = 'https://gergobalogh.me/'
languageCode = 'en-us'
title = 'Gergő Balogh'
theme = 'PaperMod'
publishDir = 'docs'

[params]
  env = "production"
  description = "Personal blog of Gergő Balogh"
  author = "Gergő Balogh"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true

  [params.assets]
    disableFingerprinting = true

  [params.homeInfoParams]
    Title = "Welcome"
    Content = "Personal blog and portfolio"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
